### ISSUE TITLE
osb-checker runs test outside of the configurated API version

### ISSUE THREAD

**Issue by marberger** [evoila/osb-checker-kotlin#13]
During usage of the osb-checker-kotlin to test compatibility of a service broker with API version 2.13, the osb-checker runs fetch binding tests although this is outside of the 2.13 spec. This is probably caused by the catalog of the broker, which contains binding_retrievable=true, because its actual supported version is >2.13. This means testing backwards compatibility is not really possible with the current state of the osb-checker-kotlin.

Will this behaviour be changed in the future?

**Comment by joStrauss** [comment]
This will be fixed, with the update to 2.15 spec.

**Comment by marberger** [comment]
API version dependent tested solved this issue.
Thank you.

Closing this issue.
