### ISSUE TITLE
response.body().jsonPath().get("operation") must not be null

### ISSUE THREAD

**Issue by mattmcneeney** [evoila/osb-checker-kotlin#19]
For all asynchronous operations, the test suite seems to require the `operation` field in the response alongside `202 Accepted`. However, according to the [spec](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#body-4), this field is not required in the responses: 
```
   ├─ BindingJUnit5 ✔
   │  ├─ runInvalidBindingAttempts() ✔
   │  │  ├─ Provision and in case of a async service broker polling, for later binding ✔
   │  │  │  ├─ Running valid PUT provision with instanceId f2aa026a-3d99-48ec-93bb-f56916aa55b8 for service 33ceba5779bfa320a1ef0694d98069df and plan small id: e8a882786ba9e223187be22c64a8720e ✘ response.body().jsonPath().get("operation") must not be null
```

This is causing our pipeline to fail. Would it be possible to fix this? Thank you!

**Comment by chbrinker** [comment]
Hi,

thanks for raising Matt. We will adjust that.

**Comment by joStrauss** [comment]
Hi,
I fixed it in this pull request
https://github.com/evoila/osb-checker-kotlin/pull/20

**Comment by mattmcneeney** [comment]
Thank you!
