### ISSUE TITLE
Service Broker Error codes are not tested

### ISSUE THREAD

**Issue by marberger** [evoila/osb-checker-kotlin#21]
During the testing of our service brokers, we were provoking a broker to return a wrong error code as a response, but the checker did not flinch. I assume that the checker does not look after error response bodies?

Can this please be added, because it is a "MUST" according to the specification?

https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#service-broker-errors

**Comment by joStrauss** [comment]
fixed on dev

**Comment by joStrauss** [comment]
Tests added on develop so far, for those where I had an idea on how to implement it. These included:

- Maintenance Info: tested of present for a positive and a negative case, for each plan.
- Async required: Sync tests now check if this code is included, when 422 gets returned.

**Comment by joStrauss** [comment]
The mentioned tests are included in release 1.1
