### ISSUE TITLE
Specifying parameters for tests

### ISSUE THREAD

**Issue by mattmcneeney** [evoila/osb-checker-kotlin#3]
Hey all,

In `README.md`, the example `application.yml` shows how the `parameters` key can be specified for different plans:
```
  parameters:
     plan-id-1-here:
        parameter1 : 1
        parameter2 : foo
      plan-id-2-here:
        parameter1 : 2
        parameter2 : bar
```

However, under the parameters section, I can see:
```
provisionParameters:
    plan-id-here:
      DB-name: db-name
```
and
```
bindingParameters:
    plan-id-here:
      key : value
```

From playing around, it seems like `provisionParameters` and `bindingParameters` works, rather than `parameters`. It might be worth making this clearer in the example config.

Thanks!

**Comment by jStraussEvoila** [comment]
Thank you, for bringing that up!

I corrected it in commit [b90bfbed3f1bb4b87b09a157f5709ab8ce292ab5](https://github.com/evoila/osb-checker-kotlin/commit/b90bfbed3f1bb4b87b09a157f5709ab8ce292ab5)
