### ISSUE TITLE
Software license is not defined

### ISSUE THREAD

**Issue by bulataleev** [evoila/osb-checker-kotlin#6]
Hello, according to [https://choosealicense.com/no-permission/](https://choosealicense.com/no-permission/) I am as user can't use this code to test OSB API or change the code. @jhiemer @dennis1987 @chphmu @latzinger can you  please, provide  license information of the kotlin checker.

**Comment by chbrinker** [comment]
Hi. Mistake from our side. We will add an Apache license.

**Comment by joStrauss** [comment]
I added the Apache license.
Thank you for reporting!
